Todo-Management-Project Progress
Aman-8273/todo-management-project pull request #1
Opened 2024-10-16 12:22 UTC by Aman-8273

2024-10-18 15:09 UTC, bhasker29 requested changes

2024-10-18 15:09 UTC, bhasker29 commented on src/components/TodoList.tsx
> +  console.log(items);
use console debug always

2024-10-18 15:09 UTC, bhasker29 commented on src/components/TodoList.tsx
> +    const newStatus = currentStatus === 'PENDING' ? 'COMPLETED' : 'PENDING';
'PENDING' ? 'COMPLETED' : 'PENDING';

Use constants

2024-10-18 15:09 UTC, bhasker29 commented on src/components/TodoList.tsx
> +            title,
Take this value from localstorage
            email: 'krips@mail.com',

2024-10-18 15:09 UTC, bhasker29 commented on src/components/TodoPage.tsx
> +          email: 'krips@mail.com',
email: 'krips@mail.com',
   take this from localstorage

2024-10-18 15:09 UTC, bhasker29 commented on src/main.tsx
> +  uri: 'https://b321-2409-40c1-5023-badb-a914-fd50-5db2-d65c.ngrok-free.app/graphql',
take this form the configurations

2024-10-18 15:26 UTC, Aman-8273 commented
Ok sir, I do it tomorrow..

On Fri, 18 Oct, 2024, 8:39 pm bhasker29, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/TodoList.tsx
> <https://github.com/Aman-8273/todo-management-project/pull/1#discussion_r1806646361>
> :
>
> >
>  const TodoList = ({ items, onDeleteTodos, handleEdit }: TodoListProps) => {
> +  console.log(items);
>
> use console debug always
> ------------------------------
>
> In src/components/TodoList.tsx
> <https://github.com/Aman-8273/todo-management-project/pull/1#discussion_r1806650233>
> :
>
> > +  //TODO
> +
> +  // Fetch todos from the backend
> +  const { refetch } = useQuery(GET_TODOS, {
> +    fetchPolicy: 'network-only', //  always fetch the new data
> +  });
> +
> +  const [updateStatus] = useMutation(CREATE_OR_UPDATE_TODO);
> +
> +  const handleStatusChange = async (
> +    id: string,
> +    currentStatus: string,
> +    title: string,
> +    description: string
> +  ) => {
> +    const newStatus = currentStatus === 'PENDING' ? 'COMPLETED' : 'PENDING';
>
> 'PENDING' ? 'COMPLETED' : 'PENDING';
>
> Use constants
> ------------------------------
>
> In src/components/TodoList.tsx
> <https://github.com/Aman-8273/todo-management-project/pull/1#discussion_r1806652464>
> :
>
> > +  const handleStatusChange = async (
> +    id: string,
> +    currentStatus: string,
> +    title: string,
> +    description: string
> +  ) => {
> +    const newStatus = currentStatus === 'PENDING' ? 'COMPLETED' : 'PENDING';
> +
> +    try {
> +      await updateStatus({
> +        variables: {
> +          input: {
> +            id,
> +            status: newStatus,
> +            email: ***@***.***',
> +            title,
>
> Take this value from localstorage
> email: ***@***.***',
> ------------------------------
>
> In src/components/TodoPage.tsx
> <https://github.com/Aman-8273/todo-management-project/pull/1#discussion_r1806656857>
> :
>
> > +    //     ? {
> +    //         ...todo,
> +    //         text: editedTask,
> +    //         description: editedDes,
> +    //         updatedDate: updatedDT,
> +    //       }
> +    //     : todo
> +    // );
> +    // setAddTodo(updatedTask);
> +
> +    //TODO
> +    await createOrUpdateTodo({
> +      variables: {
> +        input: {
> +          id,
> +          email: ***@***.***',
>
> email: ***@***.***',
> take this from localstorage
> ------------------------------
>
> In src/main.tsx
> <https://github.com/Aman-8273/todo-management-project/pull/1#discussion_r1806659262>
> :
>
> > @@ -9,7 +9,7 @@ const root = ReactDOM.createRoot(
>  );
>
>  const client = new ApolloClient({
> -  uri: 'https://graphqlapi.com/',
> +  uri: 'https://b321-2409-40c1-5023-badb-a914-fd50-5db2-d65c.ngrok-free.app/graphql',
>
> take this form the configurations
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Aman-8273/todo-management-project/pull/1#pullrequestreview-2378363921>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJJ3LVAEVMPATHZD3YFD7UTZ4EQEJAVCNFSM6AAAAABQBK3KF6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZYGM3DGOJSGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-22 11:47 UTC, Aman-8273 commented
![Screenshot (44)](https://github.com/user-attachments/assets/c231d633-297e-4026-81e0-0fecfcca2f63)

2024-10-25 11:17 UTC, merged